name: Auto message on Creating Issue.

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            Hi 😄, @${{ github.actor }} Thanks for creating  issue at Amazing Css effects, do read and follow the [Code of Conduct](https://github.com/arpit456jain/Amazing-Css-Effects/blob/master/CODE_OF_CONDUCT.md) and the [Contribution Guidelines](#) while contributing.
    
